{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omniai.fullname" . }}-secret
  labels: {{- include "omniai.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryptionKey: {{ .Values.secret.encryptionKey | quote }}
  authSecret: {{ .Values.secret.authSecret | quote }}
  postgresPassword: {{ .Values.postgres.password | quote }}
  minioPassword: {{ .Values.minio.rootPassword | quote }}
  bootstrapAdminPassword: {{ .Values.config.bootstrapAdminPassword | quote }}
{{- end }}
